name: Publish
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/agentic-layer-sdk-adk
    permissions:
      id-token: write

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v6'

      - name: Install uv
        uses: 'astral-sh/setup-uv@v7'
        with:
          version: "0.10.7"
          enable-cache: true

      - name: Setup Python
        uses: 'actions/setup-python@v6'
        with:
          python-version-file: "adk/pyproject.toml"

      - name: uv Version Bump
        run: |-
          VERSION=${{ github.ref_name }}
          uv version --directory shared "${VERSION#v}"
          uv version --directory adk "${VERSION#v}"
          uv version --directory msaf "${VERSION#v}"

      - name: 'Build shared package'
        working-directory: shared
        run: uv build

      - name: 'Build adk package'
        working-directory: adk
        run: uv build

      - name: 'Build msaf package'
        working-directory: msaf
        run: uv build

      - name: 'Publish shared package to PyPI'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: shared/dist

      - name: 'Publish adk package to PyPI'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: adk/dist

      - name: 'Publish msaf package to PyPI'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: msaf/dist
