name: Push
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

env:
  WORKLOAD_IDENTITY_PROVIDER: 'projects/363137235362/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-actions-provider'
  SERVICE_ACCOUNT: 'sa-github-actions@agentic-layer.iam.gserviceaccount.com'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
        with:
          fetch-depth: 0 # required to fetch all history for all branches and tags
